import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <Toaster
          position="top-right"
          toastOptions={{
            style: {
              background: '#000000',
              color: '#c4b5fd',
              border: '1px solid rgba(196, 181, 253, 0.15)',
              borderRadius: '12px',
              fontSize: '12px',
              fontWeight: '600',
              letterSpacing: '0.025em',
              padding: '16px',
              backdropFilter: 'blur(16px)',
              boxShadow: '0 20px 50px rgba(0, 0, 0, 0.6), 0 0 30px rgba(196, 181, 253, 0.03)',
            },
          }}
        />
        {children}
      </body>
    </html>
  );
}
