"""Add audit fields

Revision ID: 3ba67bcc7eb7
Revises: fdb5f753193a
Create Date: 2026-03-11 02:35:15.934295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba67bcc7eb7'
down_revision: Union[str, Sequence[str], None] = 'fdb5f753193a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('created_by_id', sa.UUID(), nullable=False))
    op.add_column('project', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('project', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'project', 'user', ['created_by_id'], ['id'])
    op.add_column('stack', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('stack', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('workspace', sa.Column('created_by_id', sa.UUID(), nullable=False))
    op.add_column('workspace', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('workspace', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'workspace', 'user', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace', type_='foreignkey')
    op.drop_column('workspace', 'updated_at')
    op.drop_column('workspace', 'created_at')
    op.drop_column('workspace', 'created_by_id')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('stack', 'updated_at')
    op.drop_column('stack', 'created_at')
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'updated_at')
    op.drop_column('project', 'created_at')
    op.drop_column('project', 'created_by_id')
    # ### end Alembic commands ###
