"""Add GitHub fields to Workspace

Revision ID: 3d393a2e42fa
Revises: 5f075491ced5
Create Date: 2026-03-11 01:54:35.759422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d393a2e42fa'
down_revision: Union[str, Sequence[str], None] = '5f075491ced5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('github_id', sa.String(), nullable=True))
    op.add_column('workspace', sa.Column('github_access_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace', 'github_access_token')
    op.drop_column('workspace', 'github_id')
    # ### end Alembic commands ###
