"""Restore Stack model and language field

Revision ID: 40b3c18d984c
Revises: 750f89aa4435
Create Date: 2026-03-11 15:46:49.390836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b3c18d984c'
down_revision: Union[str, Sequence[str], None] = '750f89aa4435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stack',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('dockerfile_template', sa.Text(), nullable=False),
    sa.Column('default_port', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stack_id'), 'stack', ['id'], unique=False)
    op.create_index(op.f('ix_stack_name'), 'stack', ['name'], unique=True)
    op.add_column('project', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'language')
    op.drop_index(op.f('ix_stack_name'), table_name='stack')
    op.drop_index(op.f('ix_stack_id'), table_name='stack')
    op.drop_table('stack')
    # ### end Alembic commands ###
