"""Remove region instance_tier and language

Revision ID: 750f89aa4435
Revises: 7ae46c69086f
Create Date: 2026-03-11 15:19:48.684636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '750f89aa4435'
down_revision: Union[str, Sequence[str], None] = '7ae46c69086f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stack_id'), table_name='stack')
    op.drop_index(op.f('ix_stack_name'), table_name='stack')
    op.drop_table('stack')
    op.drop_column('project', 'instance_tier')
    op.drop_column('project', 'language')
    op.drop_column('project', 'region')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('instance_tier', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('stack',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dockerfile_template', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('default_port', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('icon_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('stack_pkey'))
    )
    op.create_index(op.f('ix_stack_name'), 'stack', ['name'], unique=True)
    op.create_index(op.f('ix_stack_id'), 'stack', ['id'], unique=False)
    # ### end Alembic commands ###
