"""add_deployment_fields_to_project

Revision ID: a3adfc487a94
Revises: e01a451d6e41
Create Date: 2026-03-11 03:33:31.877787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3adfc487a94'
down_revision: Union[str, Sequence[str], None] = 'e01a451d6e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('language', sa.String(), nullable=True))
    op.add_column('project', sa.Column('branch', sa.String(), nullable=True))
    op.add_column('project', sa.Column('region', sa.String(), nullable=True))
    op.add_column('project', sa.Column('root_dir', sa.String(), nullable=True))
    op.add_column('project', sa.Column('build_command', sa.String(), nullable=True))
    op.add_column('project', sa.Column('start_command', sa.String(), nullable=True))
    op.add_column('project', sa.Column('instance_tier', sa.String(), nullable=True))
    op.add_column('project', sa.Column('deploy_type', sa.String(), nullable=False))
    op.add_column('project', sa.Column('docker_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'docker_config')
    op.drop_column('project', 'deploy_type')
    op.drop_column('project', 'instance_tier')
    op.drop_column('project', 'start_command')
    op.drop_column('project', 'build_command')
    op.drop_column('project', 'root_dir')
    op.drop_column('project', 'region')
    op.drop_column('project', 'branch')
    op.drop_column('project', 'language')
    # ### end Alembic commands ###
