"""Add Workspace

Revision ID: a70874517baf
Revises: 33b7acb4dde3
Create Date: 2026-03-11 01:15:07.672446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a70874517baf'
down_revision: Union[str, Sequence[str], None] = '33b7acb4dde3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_id'), 'workspace', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_name'), 'workspace', ['name'], unique=False)
    op.create_index(op.f('ix_workspace_slug'), 'workspace', ['slug'], unique=True)
    op.add_column('project', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'project', 'workspace', ['workspace_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'workspace_id')
    op.drop_index(op.f('ix_workspace_slug'), table_name='workspace')
    op.drop_index(op.f('ix_workspace_name'), table_name='workspace')
    op.drop_index(op.f('ix_workspace_id'), table_name='workspace')
    op.drop_table('workspace')
    # ### end Alembic commands ###
