"""Make created_by a flexible string

Revision ID: e01a451d6e41
Revises: 3ba67bcc7eb7
Create Date: 2026-03-11 02:37:52.887054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e01a451d6e41'
down_revision: Union[str, Sequence[str], None] = '3ba67bcc7eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('created_by', sa.String(), nullable=True))
    op.drop_constraint(op.f('project_created_by_id_fkey'), 'project', type_='foreignkey')
    op.drop_column('project', 'created_by_id')
    op.add_column('stack', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('user', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('workspace', sa.Column('created_by', sa.String(), nullable=True))
    op.drop_constraint(op.f('workspace_created_by_id_fkey'), 'workspace', type_='foreignkey')
    op.drop_column('workspace', 'created_by_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('workspace_created_by_id_fkey'), 'workspace', 'user', ['created_by_id'], ['id'])
    op.drop_column('workspace', 'created_by')
    op.drop_column('user', 'created_by')
    op.drop_column('stack', 'created_by')
    op.add_column('project', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('project_created_by_id_fkey'), 'project', 'user', ['created_by_id'], ['id'])
    op.drop_column('project', 'created_by')
    # ### end Alembic commands ###
