"""add_repo_full_name_to_project

Revision ID: f1ea818e18f9
Revises: a3adfc487a94
Create Date: 2026-03-11 12:44:58.384708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1ea818e18f9'
down_revision: Union[str, Sequence[str], None] = 'a3adfc487a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('github_repo_full_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'github_repo_full_name')
    # ### end Alembic commands ###
