"""Remove GitHub fields from User

Revision ID: fdb5f753193a
Revises: 3d393a2e42fa
Create Date: 2026-03-11 02:33:28.013856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb5f753193a'
down_revision: Union[str, Sequence[str], None] = '3d393a2e42fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_github_id'), table_name='user')
    op.drop_column('user', 'github_access_token')
    op.drop_column('user', 'github_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('github_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('github_access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_user_github_id'), 'user', ['github_id'], unique=True)
    # ### end Alembic commands ###
